title: Autom8 with Mark

description: >
  IT Infrastructure & Automation Engineer specializing in
  PowerShell, n8n, Microsoft 365, Windows Server,
  Hyper-V, and IT process automation.

theme: minima

header_pages:
  - about.md
  - projects.md
  - contact.md
  - resume.md
  - blog.md
